export const CART_REQUEST = "CART_REQUEST";
export const CART_FAILURE = "CART_FAILURE";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS";
