export const BOOKINGS_REQUEST = "BOOKINGS_REQUEST";
export const BOOKINGS_FAILURE = "BOOKINGS_FAILURE";

export const FETCH_BOOKINGS_SUCCESS = "FETCH_BOOKINGS_SUCCESS";
export const DELETE_BOOKING = "DELETE_BOOKING";
