export const CART_REQUEST = "CART_REQUEST";
export const CART_FAILURE = "CART_FAILURE";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const REMOVE_HOTEL_CART_ITEM = "REMOVE_HOTEL_CART_ITEM";
export const REMOVE_FLIGHT_CART_ITEM = "REMOVE_FLIGHT_CART_ITEM";
export const CLEAR_CART = "CLEAR_CART";
